### ISSUE TITLE
Fails latest release

### ISSUE THREAD

**Issue by Simbiat** [viion/lodestone-php#40]
On latest release I get the following error when trying to get FreeCompany data:
```
PHP Warning:  dom_import_simplexml() expects parameter 1 to be object, boolean given in root\\backend\\Lodestone\\Dom\\Document.php on line 94, referer: http://192.168.1.5/fftracker/
PHP Notice:  Trying to get property of non-object in root\\backend\\Lodestone\\Dom\\Document.php on line 94, referer: http://192.168.1.5/fftracker/
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to DOMXPath::__construct() must be an instance of DOMDocument, null given in root\\backend\\Lodestone\\Dom\\Document.php:156\nStack trace:\n#0 root\\backend\\Lodestone\\Dom\\Document.php(156): DOMXPath->__construct(NULL)\n#1 root\\backend\\Lodestone\\Parser\\FreeCompany.php(43): Lodestone\\Dom\\Document->find('.entry__freecom...')\n#2 root\\backend\\Lodestone\\Parser\\FreeCompany.php(26): Lodestone\\Parser\\FreeCompany->parseHeader()\n#3 root\\backend\\fftracker.php(1321): Lodestone\\Parser\\FreeCompany->parse()\n#4 root\\backend\\fftracker.php(20): lodestone_grab('923463103592321...', 'freecompany')\n#5 C:\\Users\\simbi\\On in root\\backend\\Lodestone\\Dom\\Document.php on line 156, referer: http://192.168.1.5/fftracker/
```
When getting Free Company members:
```
PHP Fatal error:  Uncaught Error: Call to undefined method Lodestone\\Parser\\FreeCompanyMembers::add() in root\\backend\\Lodestone\\Parser\\FreeCompanyMembers.php:51\nStack trace:\n#0 root\\backend\\Lodestone\\Parser\\FreeCompanyMembers.php(32): Lodestone\\Parser\\FreeCompanyMembers->pageCount()\n#1 root\\backend\\fftracker.php(1322): Lodestone\\Parser\\FreeCompanyMembers->parse()\n#2 root\\backend\\fftracker.php(20): lodestone_grab('923463103592321...', 'freecompany')\n#3 root\\index.php(228): ff_id_gateway('923463103592321...', 'freecompany')\n#4 {main}\n  thrown in root\\backend\\Lodestone\\Parser\\FreeCompanyMembers.php on line 51, referer: http://192.168.1.5/fftracker/
```

For linkshell:
```
PHP Warning:  dom_import_simplexml() expects parameter 1 to be object, boolean given in root\\backend\\Lodestone\\Dom\\Document.php on line 94, referer: http://192.168.1.5/fftracker/
PHP Notice:  Trying to get property of non-object in root\\backend\\Lodestone\\Dom\\Document.php on line 94, referer: http://192.168.1.5/fftracker/
Uncaught TypeError: Argument 1 passed to DOMXPath::__construct() must be an instance of DOMDocument, null given in root\\backend\\Lodestone\\Dom\\Document.php:156\nStack trace:\n#0 root\\backend\\Lodestone\\Dom\\Document.php(156): DOMXPath->__construct(NULL)\n#1 root\\backend\\Lodestone\\Parser\\Linkshell.php(32): Lodestone\\Dom\\Document->find('.heading__links...')\n#2 root\\backend\\fftracker.php(1336): Lodestone\\Parser\\Linkshell->parse()\n#3 root\\backend\\fftracker.php(20): lodestone_grab('225179981369131...', 'linkshell')\n#4 root\\index.php(228): ff_id_gateway('923463103592321...', 'freecompany')\n#5 {main}\n  thrown in root\\backend\\Lodestone\\Dom\\Document.php on line 156, referer: http://192.168.1.5/fftracker/
```

This is what I get when trying to get character data:
```
PHP Fatal error:  Uncaught Error: Call to protected Lodestone\\Validator\\BaseValidator::__construct() from context 'Lodestone\\Parser\\ParserHelper' in root\\backend\\Lodestone\\Parser\\ParserHelper.php:50\nStack trace:\n#0 root\\backend\\Lodestone\\Parser\\Character.php(31): Lodestone\\Parser\\ParserHelper->ensureHtml()\n#1 root\\backend\\fftracker.php(1320): Lodestone\\Parser\\Character->parse()\n#2 root\\backend\\fftracker.php(20): lodestone_grab('6691027', 'character')\n#3 root\\index.php(228): ff_id_gateway('923463103592321...', 'freecompany')\n#4 {main}\n  thrown in root\\backend\\Lodestone\\Parser\\ParserHelper.php on line 50, referer: http://192.168.1.5/fftracker/
```

I will check this when I am back from work, but for reference this is my code for lodestone_grab, where they all fail:
```php
function lodestone_grab($id, $type) {
	if ($type == "character") {
		$parser = new Lodestone\Parser\Character();
	} elseif ($type == "freecompany") {
		$parser = new Lodestone\Parser\FreeCompany();
		$parserm = new Lodestone\Parser\FreeCompanyMembers();
	} elseif ($type == "linkshell") {
		$parser = new Lodestone\Parser\Linkshell();
	}
	$attempts = 0;
	do {
		try {
			if ($type == "character") {
				$fcdatatmp = $parser->url(sprintf(\Lodestone\Modules\Routes::LODESTONE_CHARACTERS_URL, $id))->parse();
			} elseif ($type == "freecompany") {
				$members = $parserm->url(sprintf(\Lodestone\Modules\Routes::LODESTONE_FREECOMPANY_MEMBERS_URL, $id))->parse();
				if ($members !== false || $members['page_total'] > 1) {
					for ($i = 2; $i <= $members['page_total']; $i++) {
						$memberspage = $parserm->url(sprintf(\Lodestone\Modules\Routes::LODESTONE_FREECOMPANY_MEMBERS_URL, $id)."?page=".$i)->parse();
						if ($memberspage === false) {
							$members = false;
						} else {
							$members['members'] = array_merge($members['members'], $memberspage['members']);
						}
					}
				}
				if ($members !== false) {
					$fcdatatmp['members'] = $members['members'];
				}
			} elseif ($type == "linkshell") {
				$fcdatatmp = $parser->url(sprintf(\Lodestone\Modules\Routes::LODESTONE_LINKSHELL_MEMBERS_URL, $id))->parse();
				if ($fcdatatmp !== false || $fcdatatmp['page_total'] > 1) {
					for ($i = 2; $i <= $fcdatatmp['page_total']; $i++) {
						$memberspage = $parser->url(sprintf(\Lodestone\Modules\Routes::LODESTONE_LINKSHELL_MEMBERS_URL, $id)."?page=".$i)->parse();
						if ($memberspage === false) {
							$fcdatatmp = false;
						} else {
							$fcdatatmp['members'] = array_merge($fcdatatmp['members'], $memberspage['members']);
						}
					}
				}
			}
		} catch (\Lodestone\Validator\ValidationException $ex) {
			if ($ex->getMessage() == "Requested page is not available") {
				return 404;
			}
			$attempts++;
			sleep(5);
			continue;
		}
		break;
	} while($attempts < 5);
	if (!isset($fcdatatmp['name']) || is_null($fcdatatmp['name'])) {
		return false;
	} else {
		$fcdatatmp['id'] = $id;
		return $fcdatatmp;
	}
}
```

**Comment by viion** [comment]
I will have a look, I think I need to create a `dev` branch as the code on `master` isn't stable, only those in the `releases` tab should be considered stable. 

I canfix this though :D

**Comment by shentschel** [comment]
Here are the reformated error messages for a better readability:

**FreeCompany Data**:
```
PHP Warning:  dom_import_simplexml() expects parameter 1 to be object, boolean given in root\\backend\\Lodestone\\Dom\\Document.php on line 94, referer: http://192.168.1.5/fftracker/
PHP Notice:  Trying to get property of non-object in root\\backend\\Lodestone\\Dom\\Document.php on line 94, referer: http://192.168.1.5/fftracker/
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to DOMXPath::__construct() must be an instance of DOMDocument, null given in root\\backend\\Lodestone\\Dom\\Document.php:156
Stack trace:
#0 root\\backend\\Lodestone\\Dom\\Document.php(156): DOMXPath->__construct(NULL)
#1 root\\backend\\Lodestone\\Parser\\FreeCompany.php(43): Lodestone\\Dom\\Document->find('.entry__freecom...')
#2 root\\backend\\Lodestone\\Parser\\FreeCompany.php(26): Lodestone\\Parser\\FreeCompany->parseHeader()
#3 root\\backend\\fftracker.php(1321): Lodestone\\Parser\\FreeCompany->parse()
#4 root\\backend\\fftracker.php(20): lodestone_grab('923463103592321...', 'freecompany')
#5 C:\\Users\\simbi\\On in root\\backend\\Lodestone\\Dom\\Document.php on line 156, referer: http://192.168.1.5/fftracker/
```

**FC Member**
```
PHP Fatal error:  Uncaught Error: Call to undefined method Lodestone\\Parser\\FreeCompanyMembers::add() in root\\backend\\Lodestone\\Parser\\FreeCompanyMembers.php:51
Stack trace:
#0 root\\backend\\Lodestone\\Parser\\FreeCompanyMembers.php(32): Lodestone\\Parser\\FreeCompanyMembers->pageCount()
#1 root\\backend\\fftracker.php(1322): Lodestone\\Parser\\FreeCompanyMembers->parse()
#2 root\\backend\\fftracker.php(20): lodestone_grab('923463103592321...', 'freecompany')
#3 root\\index.php(228): ff_id_gateway('923463103592321...', 'freecompany')
#4 {main}
  thrown in root\\backend\\Lodestone\\Parser\\FreeCompanyMembers.php on line 51, referer: http://192.168.1.5/fftracker/
```

**Linkshell**
```
PHP Warning:  dom_import_simplexml() expects parameter 1 to be object, boolean given in root\\backend\\Lodestone\\Dom\\Document.php on line 94, referer: http://192.168.1.5/fftracker/
PHP Notice:  Trying to get property of non-object in root\\backend\\Lodestone\\Dom\\Document.php on line 94, referer: http://192.168.1.5/fftracker/
Uncaught TypeError: Argument 1 passed to DOMXPath::__construct() must be an instance of DOMDocument, null given in root\\backend\\Lodestone\\Dom\\Document.php:156
Stack trace:
#0 root\\backend\\Lodestone\\Dom\\Document.php(156): DOMXPath->__construct(NULL)
#1 root\\backend\\Lodestone\\Parser\\Linkshell.php(32): Lodestone\\Dom\\Document->find('.heading__links...')
#2 root\\backend\\fftracker.php(1336): Lodestone\\Parser\\Linkshell->parse()
#3 root\\backend\\fftracker.php(20): lodestone_grab('225179981369131...', 'linkshell')
#4 root\\index.php(228): ff_id_gateway('923463103592321...', 'freecompany')
#5 {main}
  thrown in root\\backend\\Lodestone\\Dom\\Document.php on line 156, referer: http://192.168.1.5/fftracker/
```

**Character Data**:
```
Uncaught Error: Call to protected Lodestone\\Validator\\BaseValidator::__construct() from context 'Lodestone\\Parser\\ParserHelper' in root\\backend\\Lodestone\\Parser\\ParserHelper.php:50
Stack trace:
#0 root\\backend\\Lodestone\\Parser\\Character.php(31): Lodestone\\Parser\\ParserHelper->ensureHtml()
#1 root\\backend\\fftracker.php(1320): Lodestone\\Parser\\Character->parse()
#2 root\\backend\\fftracker.php(20): lodestone_grab('6691027', 'character')
#3 root\\index.php(228): ff_id_gateway('923463103592321...', 'freecompany')
#4 {main}
  thrown in root\\backend\\Lodestone\\Parser\\ParserHelper.php on line 50, referer: http://192.168.1.5/fftracker/
```

**Comment by viion** [comment]
Could you try again? This should be working now.

**Comment by Simbiat** [comment]
Company (data is returned, though):
```
PHP Warning:  Missing argument 1 for Lodestone\\Parser\\FreeCompany::parse(), called in root\\backend\\fftracker.php on line 1324 and defined in root\\backend\\Lodestone\\Parser\\FreeCompany.php on line 17, referer: http://192.168.1.5/fftracker/
PHP Notice:  Undefined variable: id in root\\backend\\Lodestone\\Parser\\FreeCompany.php on line 20, referer: http://192.168.1.5/fftracker/
```
Linkshell:
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Lodestone\\Parser\\Linkshell::parse() must be of the type integer, none given, called in root\\backend\\fftracker.php on line 1340 and defined in root\\backend\\Lodestone\\Parser\\Linkshell.php:18
Stack trace:
#0 root\\backend\\fftracker.php(1340): Lodestone\\Parser\\Linkshell->parse()
#1 root\\backend\\fftracker.php(21): lodestone_grab('225179981369131...', 'linkshell')
#2 root\\index.php(228): ff_id_gateway('923463103592321...', 'freecompany')
#3 {main}\n  thrown in root\\backend\\Lodestone\\Parser\\Linkshell.php on line 18, referer: http://192.168.1.5/fftracker/

```
Character:
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Lodestone\\Parser\\Character\\Parser::__construct() must be of the type integer, none given, called in root\\backend\\fftracker.php on line 1311 and defined in root\\backend\\Lodestone\\Parser\\Character\\Parser.php:39
Stack trace:
#0 root\\backend\\fftracker.php(1311): Lodestone\\Parser\\Character\\Parser->__construct()
#1 root\\backend\\fftracker.php(22): lodestone_grab('6691027', 'character')
#2 root\\index.php(228): ff_id_gateway('923463103592321...', 'freecompany')
#3 {main}\n  thrown in root\\backend\\Lodestone\\Parser\\Character\\Parser.php on line 39, referer: http://192.168.1.5/fftracker/
```

Current (updated) lodestone_grab:
```php
function lodestone_grab($id, $type) {
	if ($type == "character") {
		$parser = new Lodestone\Parser\Character\Parser();
	} elseif ($type == "freecompany") {
		$parser = new Lodestone\Parser\FreeCompany();
		$parserm = new Lodestone\Parser\FreeCompanyMembers();
	} elseif ($type == "linkshell") {
		$parser = new Lodestone\Parser\Linkshell();
	}
	$attempts = 0;
	do {
		try {
			if ($type == "character") {
				$fcdatatmp = (array)$parser->url(sprintf(\Lodestone\Modules\Routes::LODESTONE_CHARACTERS_URL, $id))->parse();
			} elseif ($type == "freecompany") {
				$fcdatatmp = (array)$parser->url(sprintf(\Lodestone\Modules\Routes::LODESTONE_FREECOMPANY_URL, $id))->parse();
				$members = (array)$parserm->url(sprintf(\Lodestone\Modules\Routes::LODESTONE_FREECOMPANY_MEMBERS_URL, $id))->parse();
				if ($members !== false || $members['page_total'] > 1) {
					for ($i = 2; $i <= $members['page_total']; $i++) {
						$memberspage = (array)$parserm->url(sprintf(\Lodestone\Modules\Routes::LODESTONE_FREECOMPANY_MEMBERS_URL, $id)."?page=".$i)->parse();
						if ($memberspage === false) {
							$members = false;
						} else {
							$members['members'] = array_merge($members['members'], $memberspage['members']);
						}
					}
				}
				if ($members !== false) {
					$fcdatatmp['members'] = $members['members'];
				}
			} elseif ($type == "linkshell") {
				$fcdatatmp = (array)$parser->url(sprintf(\Lodestone\Modules\Routes::LODESTONE_LINKSHELL_MEMBERS_URL, $id))->parse();
				if ($fcdatatmp !== false || $fcdatatmp['page_total'] > 1) {
					for ($i = 2; $i <= $fcdatatmp['page_total']; $i++) {
						$memberspage = (array)$parser->url(sprintf(\Lodestone\Modules\Routes::LODESTONE_LINKSHELL_MEMBERS_URL, $id)."?page=".$i)->parse();
						if ($memberspage === false) {
							$fcdatatmp = false;
						} else {
							$fcdatatmp['members'] = array_merge($fcdatatmp['members'], $memberspage['members']);
						}
					}
				}
			}
		} catch (\Lodestone\Validator\ValidationException $ex) {
			if ($ex->getMessage() == "Requested page is not available") {
				return 404;
			}
			$attempts++;
			sleep(5);
			continue;
		}
		break;
	} while($attempts < 5);
	if (!isset($fcdatatmp['name']) || is_null($fcdatatmp['name'])) {
		return false;
	} else {
		$fcdatatmp['id'] = $id;
		return $fcdatatmp;
	}
}
```

Ignore "freecompany" in stack traces - that's just me calling a proper webpage. test data is forced down the line.

**Comment by viion** [comment]
You should use the API class or pass the id to parse/construct, if you have a look at api.pho you can see how it's done :)

**Comment by Simbiat** [comment]
In that case it works with no errors/warnings, but, when converting to an array character has keys, that I do not like...
```array(20) { ["*id"]=> int(6691027) ["*name"]=> string(16) "Besputha Tomkova" ["*server"]=> string(10) "Blackblood" ["*title"]=> string(10) "Blackblood" ["*avatar"]=> string(112) "http://img2.finalfantasyxiv.com/f/fb38cb1e40a18da7a3527d8f8fe5e1b6_777c57311d510ca65dac3c1077dee435fc0_96x96.jpg" ["*portrait"]=> string(114) "http://img2.finalfantasyxiv.com/f/fb38cb1e40a18da7a3527d8f8fe5e1b6_777c57311d510ca65dac3c1077dee435fl0_640x873.jpg" ["*biography"]=> string(25) "pads:ef70bbbdd77871be10d4" ["*race"]=> string(11) "Miqo'te" ["*clan"]=> string(18) "Keeper of the Moon" ["*gender"]=> string(6) "female" ["*nameday"]=> string(31) "12th Sun of the 3rd Astral Moon" ["*guardian"]=> NULL ["*city"]=> object(Lodestone\Entities\Character\City)#385 (3) { ["id":protected]=> int(3) ["name":protected]=> string(6) "Ul'dah" ["icon":protected]=> NULL } ["*grandcompany"]=> NULL ["*freecompany"]=> string(19) "9234631035923213559" ["*classjobs"]=> array(23) { [1]=> object(Lodestone\Entities\Character\ClassJob)#347 (9) { ["id":protected]=> int(1) ["name":protected]=> string(9) "Gladiator" ["level":protected]=> int(60) ["expLevel":protected]=> int(0) ["expLevelTogo":protected]=> int(0) ["expLevelMax":protected]=> int(0) ["expTotal":protected]=> int(29470800) ["expTotalMax":protected]=> int(29470800) ["expTotalTogo":protected]=> int(0) } [2]=> object(Lodestone\Entities\Character\ClassJob)#331 (9) { ["id":protected]=> int(2) ["name":protected]=> string(8) "Pugilist" ["level":protected]=> int(60) ["expLevel":protected]=> int(0) ["expLevelTogo":protected]=> int(0) ["expLevelMax":protected]=> int(0) ["expTotal":protected]=> int(29470800) ["expTotalMax":protected]=> int(29470800) ["expTotalTogo":protected]=> int(0) } [3]=> object(Lodestone\Entities\Character\ClassJob)#358 (9) { ["id":protected]=> int(3) ["name":protected]=> string(8) "Marauder" ["level":protected]=> int(60) ["expLevel":protected]=> int(0) ["expLevelTogo":protected]=> int(0) ["expLevelMax":protected]=> int(0) ["expTotal":protected]=> int(29470800) ["expTotalMax":protected]=> int(29470800) ["expTotalTogo":protected]=> int(0) } [4]=> object(Lodestone\Entities\Character\ClassJob)#338 (9) { ["id":protected]=> int(4) ["name":protected]=> string(6) "Lancer" ["level":protected]=> int(60) ["expLevel":protected]=> int(0) ["expLevelTogo":protected]=> int(0) ["expLevelMax":protected]=> int(0) ["expTotal":protected]=> int(29470800) ["expTotalMax":protected]=> int(29470800) ["expTotalTogo":protected]=> int(0) } [5]=> object(Lodestone\Entities\Character\ClassJob)#330 (9) { ["id":protected]=> int(5) ["name":protected]=> string(6) "Archer" ["level":protected]=> int(60) ["expLevel":protected]=> int(0) ["expLevelTogo":protected]=> int(0) ["expLevelMax":protected]=> int(0) ["expTotal":protected]=> int(29470800) ["expTotalMax":protected]=> int(29470800) ["expTotalTogo":protected]=> int(0) } [29]=> object(Lodestone\Entities\Character\ClassJob)#357 (9) { ["id":protected]=> int(29) ["name":protected]=> string(5) "Rogue" ["level":protected]=> int(60) ["expLevel":protected]=> int(0) ["expLevelTogo":protected]=> int(0) ["expLevelMax":protected]=> int(0) ["expTotal":protected]=> int(29470800) ["expTotalMax":protected]=> int(29470800) ["expTotalTogo":protected]=> int(0) } [6]=> object(Lodestone\Entities\Character\ClassJob)#359 (9) { ["id":protected]=> int(6) ["name":protected]=> string(8) "Conjurer" ["level":protected]=> int(60) ["expLevel":protected]=> int(0) ["expLevelTogo":protected]=> int(0) ["expLevelMax":protected]=> int(0) ["expTotal":protected]=> int(29470800) ["expTotalMax":protected]=> int(29470800) ["expTotalTogo":protected]=> int(0) } [7]=> object(Lodestone\Entities\Character\ClassJob)#373 (9) { ["id":protected]=> int(7) ["name":protected]=> string(11) "Thaumaturge"....

```
I truncated it obviously. A lot of them has that "protected" stuff or star. Some class names are represented as objects, not actual names, as well. In fact seems like all "entities" are like that in the output. I know what that means, but question is whether I can somehow convert this whole object into a proper array? I mean like in 1 go.

**Comment by viion** [comment]
How are you truncating to an array? it has a `toArray` method

```
$api = new \Lodestone\Api;
$character = $api->getCharacter('<id>');
$array = $character->toArray();
```

You're probably trying to cast an array over an Object.

**Comment by viion** [comment]
I've added `toArray` info to the readme.

**Comment by Simbiat** [comment]
It makes it a bit inconsistent with others, but ok... Still, toArray returns way less than expected:
```
array (
  'id' => '6691027',
  'name' => 'Besputha Tomkova',
  'server' => 'Blackblood',
  'title' => 'Blackblood',
  'avatar' => 'http://img2.finalfantasyxiv.com/f/fb38cb1e40a18da7a3527d8f8fe5e1b6_777c57311d510ca65dac3c1077dee435fc0_96x96.jpg',
  'portrait' => 'http://img2.finalfantasyxiv.com/f/fb38cb1e40a18da7a3527d8f8fe5e1b6_777c57311d510ca65dac3c1077dee435fl0_640x873.jpg',
  'biography' => 'pads:ef70bbbdd77871be10d4',
  'race' => 'Miqo'te',
  'clan' => 'Keeper of the Moon',
  'gender' => 'female',
  'nameday' => '12th Sun of the 3rd Astral Moon',
  'city' => 
  array (
    'id' => 3,
    'name' => 'Ul\'dah',
  ),
  'freecompany' => '9234631035923213559',
  'classjobs' => 
  array (
    'id' => 18,
    'name' => 'Fisher',
    'level' => 60,
    'expTotal' => 29470800,
    'expTotalMax' => 29470800,
  ),
  'attributes' => 
  array (
    'id' => 42.0,
    'name' => 'Water',
  ),
  'collectables' => 
  array (
    'minions' => 
    array (
      'id' => 206,
      'name' => 'Manjimutt',
    ),
    'mounts' => 
    array (
      'id' => 94,
      'name' => 'Whisper A-go-go',
    ),
  ),
  'gear' => 
  array (
    'id' => 8574,
    'lodestoneId' => 'b95eca0caf9',
    'name' => 'Soul of the Machinist',
    'slot' => 'soulcrystal',
    'category' => 'Soul Crystal',
  ),
  'activeClassJob' => 
  array (
    'id' => 31,
    'name' => 'Machinist',
    'level' => 60,
    'expTotal' => 29470800,
    'expTotalMax' => 29470800,
  ),
)
```
Seems like where it has to work with arrays it gets only last object, instead of adding them. This is easily corrected, though. I will make a pull in a moment.
Character information is now missing Grand Company info and Guardian, though. Will create separate issue for that one after closing this.
